<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>js</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$|\[\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}|^\s*\]</string>
	<key>name</key>
	<string>Enyo 2</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.enyo2</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.animation</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(enyo)\.(easing)\.(cubicIn|cubicOut|expoOut|linear|quadInOut)\b</string>
			<key>name</key>
			<string>support.constant.animation</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string></string>
				</dict>
			</dict>
			<key>match</key>
			<string>\.\$(?=\.|\[|\s)</string>
			<key>name</key>
			<string>support.constant.other</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.enyo2</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match kind declaration</string>
			<key>match</key>
			<string>(enyo)\.(kind|depends|log|warn|error|setLogLevel|setObject|getObject|irand|cap|uncap|format|isString|isFunction|indexOf|remove|forEach|map|filter|cloneArray|clone|mixin|bind|asyncMethod|call|job|job\.stop|macroize|quickMacroize|requestAnimationFrame|cancelRequestAnimationFrame|easedLerp|createFromKind|getCookie|setCookie|requiresWindow)</string>
			<key>name</key>
			<string>support.function.core.enyo2</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.eventFlag.enyo2</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match event declaration (on/do)</string>
			<key>match</key>
			<string>(on|do)([A-Z][\w]+)</string>
			<key>name</key>
			<string>support.variable.event.enyo2</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>match kind properties</string>
			<key>match</key>
			<string>(tag|kind|name|published|statics|classes|events|handlers|components):</string>
			<key>name</key>
			<string>support.variable.kind.enyo2</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>inherited</string>
			<key>match</key>
			<string>this\.inherited\(arguments\);</string>
			<key>name</key>
			<string>support.keyword.kind.enyo2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>enyo</string>
			<key>name</key>
			<string>support.class.enyo2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.enyo2</string>
	<key>uuid</key>
	<string>8B472F8A-DA2A-4FEB-B9BE-99B2A9E363CF</string>
</dict>
</plist>
